MAX_TURNS = 1000
MAP_WIDTH = 11
MAP_HEIGHT = 11

MAX_RESOURCES = 10
RESOURCE_HEALTH = 3
GAIN_PER_RESOURCE = 6

MAX_TROOPS = 10
TROOP_DEFAULT_HEALTH = 2
TROOP_DEFAULT_DAMAGE = 1
TROOP_DEFAULT_MOVE_SPEED = 1
TROOP_POWERUP_COST = 3
TROOP_CREATION_COST = 5

BOT_STARTING_RESOURCES = 0

SPAWN_POS_BOT_1 = (2, 2)
SPAWN_POS_BOT_2 = (8, 8)
